#! /bin/sh
nitrogen --restore
$HOME/.config/polybar/launch.sh # Bar

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config focused_border_color "#0000a8"
bspc config normal_border_color "#5757ff"
bspc config active_border_color "##0000a8"

bspc config border_width         6
bspc config window_gap           0
bspc config pointer_modifier mod4

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off

nm-applet & compton # Internet selector
xset r rate 300 50 # making keys feel smoother
flameshot
